import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Section = 'card' | 'route' | 'approval' | 'preview';
type FieldType = 'Текст' | 'Число' | 'Дата' | 'Выпадающий список' | 'Множественный список' | 'Пользователь' | 'Организация' | 'Файл' | 'Ссылка' | 'Checkbox' | 'Таблица';
type Field = { id:string; title:string; code:string; type:FieldType; description:string; required:boolean; readonly:boolean; defaultValue:string; width:'25%'|'33%'|'50%'|'66%'|'100%'; hidden:boolean; position:string; display:string };
type Block = { id:string; title:string; color:string; columns:number; fields:Field[] };
type RouteNode = { id:string; title:string; type:string; x:number; y:number; executor:string; role:string; term:string; sla:string; comment:string; condition:string };
type Link = { id:string; from:string; to:string; title:string; condition:string };
type Approval = { id:string; n:number; stage:string; role:string; executor:string; condition:string; term:string; delegation:string; required:boolean; comment:string };
type Selection = { kind:'block'; id:string } | { kind:'field'; blockId:string; id:string } | { kind:'route'; id:string } | { kind:'link'; id:string } | { kind:'approval'; id:string };
const uid=()=>Math.random().toString(36).slice(2,9);
const fieldTypes:FieldType[]=['Текст','Число','Дата','Выпадающий список','Множественный список','Пользователь','Организация','Файл','Ссылка','Checkbox','Таблица'];
const nodeTypes=['Старт','Действие','Проверка','Условие','Согласование','Возврат','Завершение'];
const newField=(type:FieldType):Field=>({id:uid(),title:`Новое поле ${type}`,code:`dp_${uid()}`,type,description:'',required:false,readonly:false,defaultValue:'',width:'50%',hidden:false,position:'В блоке',display:'Обычное'});
const seedBlocks:Block[]=[{id:'b1',title:'Основная информация',color:'#eef4fb',columns:2,fields:[{...newField('Текст'),id:'f1',title:'Тема задачи',code:'task_subject',required:true,width:'100%'},{...newField('Пользователь'),id:'f2',title:'Инициатор',code:'initiator'}]},{id:'b2',title:'Дополнительные параметры',color:'#f7f8fa',columns:3,fields:[{...newField('Дата'),id:'f3',title:'Плановая дата',code:'plan_date',width:'33%'},{...newField('Организация'),id:'f4',title:'Организация',code:'company',width:'33%'}]}];
const seedRoute:RouteNode[]=[{id:'r1',type:'Старт',title:'Поступление задачи',x:52,y:85,executor:'',role:'Инициатор',term:'',sla:'',comment:'',condition:''},{id:'r2',type:'Действие',title:'Обработка',x:275,y:85,executor:'Ответственный',role:'Исполнитель',term:'2 дн.',sla:'8 ч.',comment:'',condition:''},{id:'r3',type:'Согласование',title:'Согласование',x:505,y:85,executor:'Руководитель',role:'Согласующий',term:'1 дн.',sla:'4 ч.',comment:'',condition:'task_subject заполнено'},{id:'r4',type:'Завершение',title:'Завершено',x:735,y:85,executor:'',role:'',term:'',sla:'',comment:'',condition:''}];
const seedLinks:Link[]=[{id:'l1',from:'r1',to:'r2',title:'создать',condition:''},{id:'l2',from:'r2',to:'r3',title:'на согласование',condition:'нет замечаний'},{id:'l3',from:'r3',to:'r4',title:'утверждено',condition:'все этапы пройдены'}];
function App(){const[section,setSection]=useState<Section>('card');const[blocks,setBlocks]=useState(seedBlocks);const[route,setRoute]=useState(seedRoute);const[links,setLinks]=useState(seedLinks);const[approvals,setApprovals]=useState<Approval[]>([{id:'a1',n:1,stage:'Первичное согласование',role:'Руководитель',executor:'Петров П.П.',condition:'Сумма > 0',term:'1 дн.',delegation:'Разрешено',required:true,comment:''}]);const[sel,setSel]=useState<Selection>({kind:'block',id:'b1'});const[query,setQuery]=useState('');const allFields=blocks.flatMap(b=>b.fields.map(f=>`${f.title} (${f.code})`));
const selected=useMemo(()=> sel.kind==='block'?blocks.find(b=>b.id===sel.id):sel.kind==='field'?blocks.find(b=>b.id===sel.blockId)?.fields.find(f=>f.id===sel.id):sel.kind==='route'?route.find(r=>r.id===sel.id):sel.kind==='link'?links.find(l=>l.id===sel.id):approvals.find(a=>a.id===sel.id),[sel,blocks,route,links,approvals]);
const patchBlock=(id:string,p:Partial<Block>)=>setBlocks(bs=>bs.map(b=>b.id===id?{...b,...p}:b)); const patchField=(bid:string,id:string,p:Partial<Field>)=>setBlocks(bs=>bs.map(b=>b.id===bid?{...b,fields:b.fields.map(f=>f.id===id?{...f,...p}:f)}:b)); const addBlock=()=>{const b={id:uid(),title:'Новый блок',color:'#f7f8fa',columns:2,fields:[]};setBlocks([...blocks,b]);setSel({kind:'block',id:b.id})};
const onDropField=(bid:string,e:React.DragEvent)=>{e.preventDefault();const data=e.dataTransfer.getData('text/plain');if(fieldTypes.includes(data as FieldType))patchBlock(bid,{fields:[...blocks.find(b=>b.id===bid)!.fields,newField(data as FieldType)]});else{const [from,fid]=data.split(':'); if(from&&fid&&from!==bid){const f=blocks.find(b=>b.id===from)?.fields.find(x=>x.id===fid); if(f)setBlocks(bs=>bs.map(b=>b.id===from?{...b,fields:b.fields.filter(x=>x.id!==fid)}:b.id===bid?{...b,fields:[...b.fields,f]}:b));}}};
return <div className="app"><aside className="nav"><div className="brand">1Форма</div>{[['card','Конструктор карточки'],['route','Маршрут'],['approval','Согласование'],['preview','Предпросмотр']].map(([k,t])=><button className={section===k?'active':''} onClick={()=>setSection(k as Section)}>{t}</button>)}</aside><main><header className="top"><b>Конструктор задачи · Заявка на согласование</b><div className="actions"><button>Сохранить</button><button>Отменить</button><button>Повторить</button><button>Экспорт</button><button>Импорт</button><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск"/></div></header><div className="content"><section className="work">{section==='card'&&<Card blocks={blocks} setBlocks={setBlocks} setSel={setSel} patchBlock={patchBlock} patchField={patchField} addBlock={addBlock} onDropField={onDropField}/>} {section==='route'&&<Route route={route} setRoute={setRoute} links={links} setLinks={setLinks} setSel={setSel}/>} {section==='approval'&&<Approval approvals={approvals} setApprovals={setApprovals} setSel={setSel} query={query}/>} {section==='preview'&&<Preview blocks={blocks} approvals={approvals} route={route}/>}</section><Properties sel={sel} item={selected} allFields={allFields} patchBlock={patchBlock} patchField={patchField} patchRoute={(id,p)=>setRoute(rs=>rs.map(r=>r.id===id?{...r,...p}:r))} patchLink={(id,p)=>setLinks(ls=>ls.map(l=>l.id===id?{...l,...p}:l))} patchApproval={(id,p)=>setApprovals(as=>as.map(a=>a.id===id?{...a,...p}:a))}/></div></main></div>}
function Card(p:any){return <><div className="palette"><button onClick={p.addBlock}>+ Блок</button>{fieldTypes.map(t=><span draggable onDragStart={e=>e.dataTransfer.setData('text/plain',t)}>{t}</span>)}</div><div className="canvas">{p.blocks.map((b:Block,i:number)=><div className="block" onClick={()=>p.setSel({kind:'block',id:b.id})} style={{borderTopColor:b.color}} onDragOver={e=>e.preventDefault()} onDrop={e=>p.onDropField(b.id,e)}><div className="blockHead"><b>{b.title}</b><small>{b.columns} кол.</small><button onClick={()=>p.setBlocks((bs:Block[])=>bs.filter(x=>x.id!==b.id))}>×</button></div><div className="fields">{b.fields.map(f=><div className={'field '+(f.hidden?'muted':'')} style={{width:f.width}} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',`${b.id}:${f.id}`)} onClick={e=>{e.stopPropagation();p.setSel({kind:'field',blockId:b.id,id:f.id})}}><label>{f.title}{f.required&&' *'}</label><div>{f.type}</div><small>{f.code}</small><button onClick={e=>{e.stopPropagation();p.patchField(b.id,f.id,{hidden:!f.hidden})}}>{f.hidden?'↺':'скрыть'}</button></div>)}</div></div>)}</div></>}
function Route({route,setRoute,links,setLinks,setSel}:any){const add=(type:string)=>setRoute([...route,{id:uid(),type,title:type,x:80+route.length*40,y:230,executor:'',role:'',term:'',sla:'',comment:'',condition:''}]);return <><div className="palette">{nodeTypes.map(t=><button onClick={()=>add(t)}>+ {t}</button>)}<button onClick={()=>route.length>1&&setLinks([...links,{id:uid(),from:route[route.length-2].id,to:route[route.length-1].id,title:'переход',condition:''}])}>Связать последние</button></div><div className="routeCanvas">{links.map((l:Link)=><button className="link" onClick={()=>setSel({kind:'link',id:l.id})}>{route.find((r:RouteNode)=>r.id===l.from)?.title} → {route.find((r:RouteNode)=>r.id===l.to)?.title}: {l.title}</button>)}{route.map((n:RouteNode)=><div className="node" draggable style={{left:n.x,top:n.y}} onClick={()=>setSel({kind:'route',id:n.id})} onDragEnd={e=>setRoute((rs:RouteNode[])=>rs.map(r=>r.id===n.id?{...r,x:e.clientX-250,y:e.clientY-95}:r))}><b>{n.type}</b><span>{n.title}</span><small>{n.role} {n.sla}</small></div>)}</div></>}
function Approval({approvals,setApprovals,setSel,query}:any){const rows=approvals.filter((a:Approval)=>JSON.stringify(a).toLowerCase().includes(query.toLowerCase()));return <><div className="palette"><button onClick={()=>setApprovals([...approvals,{id:uid(),n:approvals.length+1,stage:'Новый этап',role:'',executor:'',condition:'',term:'',delegation:'Нет',required:false,comment:''}])}>+ Строка</button><button>Массовое редактирование</button><button>Фильтр</button></div><table><thead><tr>{['№','Этап','Роль','Исполнитель','Условие','Срок','Делегирование','Обязательный этап','Комментарий',''].map(h=><th>{h}</th>)}</tr></thead><tbody>{rows.map((a:Approval)=><tr draggable onClick={()=>setSel({kind:'approval',id:a.id})}><td>{a.n}</td><td>{a.stage}</td><td>{a.role}</td><td>{a.executor}</td><td>{a.condition}</td><td>{a.term}</td><td>{a.delegation}</td><td>{a.required?'Да':'Нет'}</td><td>{a.comment}</td><td><button onClick={()=>setApprovals((as:Approval[])=>as.filter(x=>x.id!==a.id))}>×</button><button onClick={()=>setApprovals((as:Approval[])=>[...as,{...a,id:uid(),n:as.length+1,stage:a.stage+' копия'}])}>⧉</button></td></tr>)}</tbody></table></>}
function Preview({blocks,approvals,route}:any){return <div className="preview"><h2>Заявка на согласование</h2>{blocks.map((b:Block)=><div className="block"><div className="blockHead"><b>{b.title}</b></div><div className="fields">{b.fields.filter(f=>!f.hidden).map(f=><div className="field" style={{width:f.width}}><label>{f.title}</label><input placeholder={f.defaultValue||f.type}/></div>)}</div></div>)}<h3>Маршрут</h3><ol>{route.map((r:RouteNode)=><li>{r.title} — {r.role}</li>)}</ol><h3>Согласование</h3><table><tbody>{approvals.map((a:Approval)=><tr><td>{a.n}</td><td>{a.stage}</td><td>{a.executor}</td><td>{a.required?'обязательно':''}</td></tr>)}</tbody></table></div>}
function Properties({sel,item,allFields,patchBlock,patchField,patchRoute,patchLink,patchApproval}:any){if(!item)return <aside className="props">Выберите элемент</aside>;const input=(k:string,v:any,fn:any,type='text')=><label>{k}<input type={type} checked={type==='checkbox'?v:undefined} value={type==='checkbox'?undefined:v} onChange={e=>fn(type==='checkbox'?e.currentTarget.checked:e.currentTarget.value)}/></label>;return <aside className="props"><h3>Свойства</h3><small>{sel.kind}</small>{sel.kind==='block'&&<>{input('Название',item.title,(v:string)=>patchBlock(item.id,{title:v}))}{input('Цвет',item.color,(v:string)=>patchBlock(item.id,{color:v}),'color')}<label>Колонки<select value={item.columns} onChange={e=>patchBlock(item.id,{columns:+e.target.value})}><option>1</option><option>2</option><option>3</option><option>4</option></select></label></>}{sel.kind==='field'&&<>{input('Название',item.title,(v:string)=>patchField(sel.blockId,item.id,{title:v}))}{input('Системный код',item.code,(v:string)=>patchField(sel.blockId,item.id,{code:v}))}<label>Тип<select value={item.type} onChange={e=>patchField(sel.blockId,item.id,{type:e.target.value})}>{fieldTypes.map(t=><option>{t}</option>)}</select></label>{input('Описание',item.description,(v:string)=>patchField(sel.blockId,item.id,{description:v}))}{input('Обязательное',item.required,(v:boolean)=>patchField(sel.blockId,item.id,{required:v}),'checkbox')}{input('Только чтение',item.readonly,(v:boolean)=>patchField(sel.blockId,item.id,{readonly:v}),'checkbox')}{input('По умолчанию',item.defaultValue,(v:string)=>patchField(sel.blockId,item.id,{defaultValue:v}))}<label>Ширина<select value={item.width} onChange={e=>patchField(sel.blockId,item.id,{width:e.target.value})}>{['25%','33%','50%','66%','100%'].map(w=><option>{w}</option>)}</select></label>{input('Расположение',item.position,(v:string)=>patchField(sel.blockId,item.id,{position:v}))}{input('Отображение',item.display,(v:string)=>patchField(sel.blockId,item.id,{display:v}))}</>}{sel.kind==='route'&&<>{['title','executor','role','term','sla','comment','condition'].map(k=>input(k,item[k],(v:string)=>patchRoute(item.id,{[k]:v}))) }<label>Доступные ДП<select>{allFields.map((f:string)=><option>{f}</option>)}</select></label></>}{sel.kind==='link'&&<>{input('Название перехода',item.title,(v:string)=>patchLink(item.id,{title:v}))}{input('Условие',item.condition,(v:string)=>patchLink(item.id,{condition:v}))}</>}{sel.kind==='approval'&&<>{['stage','role','executor','condition','term','delegation','comment'].map(k=>input(k,item[k],(v:string)=>patchApproval(item.id,{[k]:v})))}{input('Обязательный',item.required,(v:boolean)=>patchApproval(item.id,{required:v}),'checkbox')}</>}</aside>}
createRoot(document.getElementById('root')!).render(<App/>);
